In [7]:
# import gensim.downloader as api

# model = api.load("word2vec-google-news-300")

In [ ]:
# word_vectors = model

# print(word_vectors['computer'])
# print(word_vectors['cat'].shape)


In [10]:
# # King + Woman - Man = ?
# word_vectors.most_similar(
#     positive=['king','women'],
#     negative=['man']
# )

In [11]:
# # King + Woman - Man = ?
# word_vectors.most_similar(
#     positive=['king','women'],
#     negative=['man'],
#     topn=10
# )

In [12]:
# word_vectors.most_similar('cat',topn=5)

In [13]:
# word_vectors.similarity('woman','man')

### Creating Token Embeddings

In [1]:
import torch

In [2]:
input_ids = torch.tensor([2,3,5,1])

vocab_size = 6 # row of embd matrix
output_dim = 3 # cols ...

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [6]:
print(embedding_layer.weight) # the initial weights

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [23]:
embedding_layer(torch.tensor([4])) # vector for the 4th row 

tensor([[-1.1589,  0.3255, -0.6315]], grad_fn=<EmbeddingBackward0>)

In [26]:
embedding_layer(input_ids)

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)