### Positional Embeddings 
#### Encoding word positions

In [1]:
import torch

In [2]:
vocab_size = 50257 # token
output_dim = 256   # vector dim

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(token_embedding_layer)

Embedding(50257, 256)


In [3]:
with open('the-verdict.txt', mode='r') as f:
    raw_data = f.read()

In [4]:
from modules import create_dataloader_v1

max_lenght = 4
dataloader = create_dataloader_v1(
    raw_data, batch_size=8, max_length=max_lenght, stride=max_lenght, shuflle=False
)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n",inputs)
print("\nTargets:\n",targets)
print(inputs.shape)

c:\Users\pc\Desktop\LLM from scratch\modules.py:68: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(self.input_ids[idx]) , torch.tensor(self.target_ids[idx])


Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])
torch.Size([8, 4])


In [5]:
token_embeddings = token_embedding_layer(inputs)
print(inputs.shape)
print(token_embeddings.shape)
print(token_embeddings[0])
print(token_embeddings[0].shape)

torch.Size([8, 4])
torch.Size([8, 4, 256])
tensor([[ 0.6400,  1.4253,  1.7338,  ...,  0.7259, -0.1415,  0.0948],
        [ 0.5959,  0.9178, -0.1582,  ..., -1.1530, -0.5945,  0.2881],
        [-0.7288,  0.1609,  1.7162,  ..., -0.6956, -0.4091,  0.0645],
        [-0.3487, -0.8503, -1.3425,  ..., -1.8181,  2.0696,  0.0907]],
       grad_fn=<SelectBackward0>)
torch.Size([4, 256])


In [6]:
context_lentgh = max_lenght
pos_embedding_layer = torch.nn.Embedding(context_lentgh, output_dim)
print(pos_embedding_layer)

pos_embeddings = pos_embedding_layer(torch.arange(max_lenght))
print(pos_embeddings)
print(pos_embeddings.shape)

Embedding(4, 256)
tensor([[ 1.3217, -0.1065,  1.3905,  ...,  1.1946,  2.1748, -0.2364],
        [ 1.0468, -0.3573, -2.0868,  ..., -0.7510,  0.9517,  1.7973],
        [-0.4868,  0.6015, -0.7261,  ...,  0.1876, -1.0858,  2.0149],
        [ 0.8868, -0.1475, -2.0278,  ..., -1.1180,  0.7815,  0.2601]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([4, 256])


In [7]:
token_embeddings[0] + pos_embeddings

tensor([[ 1.9618,  1.3188,  3.1243,  ...,  1.9206,  2.0332, -0.1417],
        [ 1.6427,  0.5605, -2.2450,  ..., -1.9040,  0.3573,  2.0854],
        [-1.2156,  0.7623,  0.9901,  ..., -0.5079, -1.4949,  2.0794],
        [ 0.5381, -0.9977, -3.3703,  ..., -2.9360,  2.8511,  0.3508]],
       grad_fn=<AddBackward0>)

In [8]:
input_embeddings = token_embeddings + pos_embeddings
print(token_embeddings.shape)
print(pos_embeddings.shape)
print(input_embeddings.shape)

torch.Size([8, 4, 256])
torch.Size([4, 256])
torch.Size([8, 4, 256])
